turbine:
  stream:
    port: 8010
  appConfig: PLANESERVICE,FLIGHTSSERVICE,fares,bookings,passengers,mail,payments
  clusterNameExpression: 'default'

server:
  port: 9009

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
